### ISSUE TITLE
How to add validation.py to Lambada/Functions/Code

### ISSUE THREAD

**Issue by TheWalkingDead1024** [alexa/alexa-smarthome-validation#3]
There is only one page I can edit, how could I add some other python files into it?There is no project concept but only one page. And " NOTE: If your skill has lock capabilities, you may need to set this timeout check to 60 seconds or more. ",how could I set this value?
![image](https://user-images.githubusercontent.com/9053681/27512734-c0dccff0-597d-11e7-9e6e-4051c8fdb3a3.png)

**Comment by dairong** [comment]
If you click on the drop down beside "Code entry type" in the screenshot above, you have the option to uploading a .zip file instead of editing inline. This allows you to zip up both your Lambda handler file as well as other dependent packages, such as the validation package, and deploy everything. For more guidance on this: http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

You can edit the value of the timeout check here: https://github.com/alexa/alexa-smarthome-validation/blob/master/python/validation.py#L227
